//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFFSSK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LFFSSK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Your Order With Our Popular Add-Ons!.
        /// </summary>
        internal static string Lbl_AddOn {
            get {
                return ResourceManager.GetString("Lbl_AddOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        internal static string Lbl_AddToCart {
            get {
                return ResourceManager.GetString("Lbl_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch screen to start.
        /// </summary>
        internal static string Lbl_Ads {
            get {
                return ResourceManager.GetString("Lbl_Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Menu.
        /// </summary>
        internal static string Lbl_Back {
            get {
                return ResourceManager.GetString("Lbl_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Lbl_BackOnly {
            get {
                return ResourceManager.GetString("Lbl_BackOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Lbl_BtnClose {
            get {
                return ResourceManager.GetString("Lbl_BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Regular.
        /// </summary>
        internal static string Lbl_BtnDownsize {
            get {
                return ResourceManager.GetString("Lbl_BtnDownsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Promo Code.
        /// </summary>
        internal static string Lbl_BtnPromoCode {
            get {
                return ResourceManager.GetString("Lbl_BtnPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade To Combo.
        /// </summary>
        internal static string Lbl_BtnUpCombo {
            get {
                return ResourceManager.GetString("Lbl_BtnUpCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade To Large.
        /// </summary>
        internal static string Lbl_BtnUpsize {
            get {
                return ResourceManager.GetString("Lbl_BtnUpsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        internal static string Lbl_BtnYes {
            get {
                return ResourceManager.GetString("Lbl_BtnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your item(s) in the cart will be cleared. Do you still want to proceed ?.
        /// </summary>
        internal static string Lbl_CancelContent {
            get {
                return ResourceManager.GetString("Lbl_CancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Lbl_CancelHeader {
            get {
                return ResourceManager.GetString("Lbl_CancelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        internal static string Lbl_CancelOrder {
            get {
                return ResourceManager.GetString("Lbl_CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment By Cash.
        /// </summary>
        internal static string Lbl_Cash {
            get {
                return ResourceManager.GetString("Lbl_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment By Credit / Debit Card.
        /// </summary>
        internal static string Lbl_CC {
            get {
                return ResourceManager.GetString("Lbl_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAY NOW.
        /// </summary>
        internal static string Lbl_Checkout {
            get {
                return ResourceManager.GetString("Lbl_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes on voucher. Please check..
        /// </summary>
        internal static string Lbl_CheckVoucher {
            get {
                return ResourceManager.GetString("Lbl_CheckVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Collected.
        /// </summary>
        internal static string Lbl_CollectPoints {
            get {
                return ResourceManager.GetString("Lbl_CollectPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Lbl_Confirmation {
            get {
                return ResourceManager.GetString("Lbl_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have any promo code to use?.
        /// </summary>
        internal static string Lbl_ContainPromoCode {
            get {
                return ResourceManager.GetString("Lbl_ContainPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD MORE.
        /// </summary>
        internal static string Lbl_ContinueOrder {
            get {
                return ResourceManager.GetString("Lbl_ContinueOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine-In.
        /// </summary>
        internal static string Lbl_DineIn {
            get {
                return ResourceManager.GetString("Lbl_DineIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Lbl_DoneOnly {
            get {
                return ResourceManager.GetString("Lbl_DoneOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Ordering.
        /// </summary>
        internal static string Lbl_DoneOrder {
            get {
                return ResourceManager.GetString("Lbl_DoneOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and register as Rooty Buddy!.
        /// </summary>
        internal static string Lbl_Download {
            get {
                return ResourceManager.GetString("Lbl_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Here.
        /// </summary>
        internal static string Lbl_DownloadHere {
            get {
                return ResourceManager.GetString("Lbl_DownloadHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change To A Regular Combo!.
        /// </summary>
        internal static string Lbl_Downsize {
            get {
                return ResourceManager.GetString("Lbl_Downsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Lbl_Edit {
            get {
                return ResourceManager.GetString("Lbl_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter promo code!.
        /// </summary>
        internal static string Lbl_EnterPromoCode {
            get {
                return ResourceManager.GetString("Lbl_EnterPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Found.
        /// </summary>
        internal static string Lbl_Error {
            get {
                return ResourceManager.GetString("Lbl_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apologies, we&apos;re experiencing issues. Please approach our staff for assistance..
        /// </summary>
        internal static string Lbl_ErrorAssist {
            get {
                return ResourceManager.GetString("Lbl_ErrorAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apologies, something went wrong. Please approach our staff for assistance..
        /// </summary>
        internal static string Lbl_ErrorAssist2 {
            get {
                return ResourceManager.GetString("Lbl_ErrorAssist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apologies, we&apos;re experiencing issues. Please try again..
        /// </summary>
        internal static string Lbl_ErrorTryAgain {
            get {
                return ResourceManager.GetString("Lbl_ErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apologies, something went wrong. Please try again..
        /// </summary>
        internal static string Lbl_ErrorTryAgain2 {
            get {
                return ResourceManager.GetString("Lbl_ErrorTryAgain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment By E-Wallet.
        /// </summary>
        internal static string Lbl_Ewallet {
            get {
                return ResourceManager.GetString("Lbl_Ewallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Pay:.
        /// </summary>
        internal static string Lbl_EwalletMethod1 {
            get {
                return ResourceManager.GetString("Lbl_EwalletMethod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Open your e-Wallet or bank app..
        /// </summary>
        internal static string Lbl_EwalletMethod2 {
            get {
                return ResourceManager.GetString("Lbl_EwalletMethod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Tap &apos;Scan&apos;..
        /// </summary>
        internal static string Lbl_EwalletMethod3 {
            get {
                return ResourceManager.GetString("Lbl_EwalletMethod3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Scan the QR code displayed on the screen to complete your payment..
        /// </summary>
        internal static string Lbl_EwalletMethod4 {
            get {
                return ResourceManager.GetString("Lbl_EwalletMethod4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR code below to pay using your e-Wallet or bank app.
        /// </summary>
        internal static string Lbl_EwalletPayment {
            get {
                return ResourceManager.GetString("Lbl_EwalletPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Voucher.
        /// </summary>
        internal static string Lbl_GiftVoucher {
            get {
                return ResourceManager.GetString("Lbl_GiftVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Lbl_GTotal {
            get {
                return ResourceManager.GetString("Lbl_GTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELLO.
        /// </summary>
        internal static string Lbl_Home {
            get {
                return ResourceManager.GetString("Lbl_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to get your food?.
        /// </summary>
        internal static string Lbl_HomeHow {
            get {
                return ResourceManager.GetString("Lbl_HomeHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Lbl_Info {
            get {
                return ResourceManager.GetString("Lbl_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert or tap your card at the payment terminal..
        /// </summary>
        internal static string Lbl_InsertPin {
            get {
                return ResourceManager.GetString("Lbl_InsertPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes on voucher or menu.Please Check..
        /// </summary>
        internal static string Lbl_InvalidMenu {
            get {
                return ResourceManager.GetString("Lbl_InvalidMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code not found!.
        /// </summary>
        internal static string Lbl_InvalidPromoCode {
            get {
                return ResourceManager.GetString("Lbl_InvalidPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Qr Code!.
        /// </summary>
        internal static string Lbl_InvalidQr {
            get {
                return ResourceManager.GetString("Lbl_InvalidQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Added.
        /// </summary>
        internal static string Lbl_ItemAdded {
            get {
                return ResourceManager.GetString("Lbl_ItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit / Debit Card.
        /// </summary>
        internal static string Lbl_KadCC {
            get {
                return ResourceManager.GetString("Lbl_KadCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Lbl_Login {
            get {
                return ResourceManager.GetString("Lbl_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Lbl_Logout {
            get {
                return ResourceManager.GetString("Lbl_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into your membership to earn rewards..
        /// </summary>
        internal static string Lbl_MemberLogin {
            get {
                return ResourceManager.GetString("Lbl_MemberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Lbl_Or {
            get {
                return ResourceManager.GetString("Lbl_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Order Number.
        /// </summary>
        internal static string Lbl_OrderNumber {
            get {
                return ResourceManager.GetString("Lbl_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment fail. Please retry payment..
        /// </summary>
        internal static string Lbl_PaymentFail {
            get {
                return ResourceManager.GetString("Lbl_PaymentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string Lbl_PaymentMethod {
            get {
                return ResourceManager.GetString("Lbl_PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick up order from the counter..
        /// </summary>
        internal static string Lbl_PickupOrder {
            get {
                return ResourceManager.GetString("Lbl_PickupOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your promo code.
        /// </summary>
        internal static string Lbl_PopUpPromoCode {
            get {
                return ResourceManager.GetString("Lbl_PopUpPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code.
        /// </summary>
        internal static string Lbl_PromoCode {
            get {
                return ResourceManager.GetString("Lbl_PromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend for you!.
        /// </summary>
        internal static string Lbl_Recommend {
            get {
                return ResourceManager.GetString("Lbl_Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding.
        /// </summary>
        internal static string Lbl_Rounding {
            get {
                return ResourceManager.GetString("Lbl_Rounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan and log in to your membership to earn rewards..
        /// </summary>
        internal static string Lbl_ScanAndLogin {
            get {
                return ResourceManager.GetString("Lbl_ScanAndLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan your membership QR code at the scanner..
        /// </summary>
        internal static string Lbl_ScanQr {
            get {
                return ResourceManager.GetString("Lbl_ScanQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! Choose Your Language To Begin.
        /// </summary>
        internal static string Lbl_SelectLanguage {
            get {
                return ResourceManager.GetString("Lbl_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Would You Like To Enjoy Your Meal?.
        /// </summary>
        internal static string Lbl_SelectOrderType {
            get {
                return ResourceManager.GetString("Lbl_SelectOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Voucher.
        /// </summary>
        internal static string Lbl_ShowVoucher {
            get {
                return ResourceManager.GetString("Lbl_ShowVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Lbl_Skip {
            get {
                return ResourceManager.GetString("Lbl_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string Lbl_Subtotal {
            get {
                return ResourceManager.GetString("Lbl_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Earn.
        /// </summary>
        internal static string Lbl_SuccessOrder {
            get {
                return ResourceManager.GetString("Lbl_SuccessOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeaway.
        /// </summary>
        internal static string Lbl_Takeaway {
            get {
                return ResourceManager.GetString("Lbl_Takeaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Have A Voucher Code?.
        /// </summary>
        internal static string Lbl_TextVoucher {
            get {
                return ResourceManager.GetString("Lbl_TextVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Timeout.
        /// </summary>
        internal static string Lbl_TimeOut {
            get {
                return ResourceManager.GetString("Lbl_TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you still want to proceed?.
        /// </summary>
        internal static string Lbl_TimeoutMsj {
            get {
                return ResourceManager.GetString("Lbl_TimeoutMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Set.
        /// </summary>
        internal static string Lbl_UpgradeCombo {
            get {
                return ResourceManager.GetString("Lbl_UpgradeCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo (L).
        /// </summary>
        internal static string Lbl_UpgradeComboL {
            get {
                return ResourceManager.GetString("Lbl_UpgradeComboL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo (R).
        /// </summary>
        internal static string Lbl_UpgradeComboR {
            get {
                return ResourceManager.GetString("Lbl_UpgradeComboR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Combo.
        /// </summary>
        internal static string Lbl_Upsize {
            get {
                return ResourceManager.GetString("Lbl_Upsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Now.
        /// </summary>
        internal static string Lbl_UseNow {
            get {
                return ResourceManager.GetString("Lbl_UseNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        internal static string Lbl_ValidUntil {
            get {
                return ResourceManager.GetString("Lbl_ValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review &amp; Pay →.
        /// </summary>
        internal static string Lbl_ViewOrder {
            get {
                return ResourceManager.GetString("Lbl_ViewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher.
        /// </summary>
        internal static string Lbl_Voucher {
            get {
                return ResourceManager.GetString("Lbl_Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Amount.
        /// </summary>
        internal static string Lbl_VoucherAmount {
            get {
                return ResourceManager.GetString("Lbl_VoucherAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome,.
        /// </summary>
        internal static string Lbl_Welcome {
            get {
                return ResourceManager.GetString("Lbl_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR TOTAL AMOUNT.
        /// </summary>
        internal static string Lbl_YourAmount {
            get {
                return ResourceManager.GetString("Lbl_YourAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Order.
        /// </summary>
        internal static string Lbl_YourOrder {
            get {
                return ResourceManager.GetString("Lbl_YourOrder", resourceCulture);
            }
        }
    }
}
